#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

typedef enum tokenType {
  TOKEN_LBRACE,   // {
  TOKEN_RBRACE,   // }
  TOKEN_LBRACKET, // [
  TOKEN_RBRACKET, // ]
  TOKEN_COLON,
  TOKEN_COMMA,
  TOKEN_PERIOD,
  TOKEN_STRING,
  TOKEN_NUMBER,
  TOKEN_TRUE,
  TOKEN_FALSE,
  TOKEN_NULL,
  TOKEN_EOF,
  TOKEN_INVALID,
  TOKEN_INVALID_LEADING_ZEROES,
  TOKEN_INVALID_ESCAPE,
  TOKEN_INVALID_HEX,
  TOKEN_INVALID_CONTROL_CHARACTERS,
  TOKEN_INVALID_UNEXPECTED_END_OF_NUMBER,
} TokenType;

const char* token_type_to_string(TokenType type);

#endif